"""initial schema (pre team-PvP baseline)

This deliberately describes the schema as it was BEFORE the team PvP mode.
A database created by the old create_all() startup can therefore be adopted
by stamping it at this revision, after which 0002 adds only the columns it
is actually missing. Fresh databases just run both in order.

Revision ID: 0001
Revises:
Create Date: 2026-09-12
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('background_url', sa.String(), nullable=True),
    sa.Column('team_color', sa.String(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('flip_h', sa.Boolean(), nullable=False),
    sa.Column('shadow', sa.Boolean(), nullable=False),
    sa.Column('outline', sa.Boolean(), nullable=False),
    sa.Column('glow', sa.Boolean(), nullable=False),
    sa.Column('idle_animation', sa.String(), nullable=False),
    sa.Column('hit_animation', sa.String(), nullable=False),
    sa.Column('heal_animation', sa.String(), nullable=False),
    sa.Column('xp_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_tiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('animation_key', sa.String(), nullable=False),
    sa.Column('damage_multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threshold')
    )
    op.create_table('gifts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gift_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('target_side', sa.String(), nullable=False),
    sa.Column('animation_key', sa.String(), nullable=False),
    sa.Column('sound_key', sa.String(), nullable=False),
    sa.Column('combo_allowed', sa.Boolean(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gift_key')
    )
    op.create_table('music_tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('battles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('side_a_character_id', sa.String(), nullable=False),
    sa.Column('side_b_character_id', sa.String(), nullable=False),
    sa.Column('background_url', sa.String(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('one_ball_per_user', sa.Boolean(), nullable=False),
    sa.Column('battle_time_seconds', sa.Integer(), nullable=True),
    sa.Column('sudden_death_enabled', sa.Boolean(), nullable=False),
    sa.Column('sudden_death_multiplier', sa.Float(), nullable=False),
    sa.Column('auto_restart', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['side_a_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['side_b_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('battle_id', sa.String(), nullable=False),
    sa.Column('side_a_xp', sa.Float(), nullable=False),
    sa.Column('side_b_xp', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('winner_side', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('damage_total', sa.Float(), nullable=False),
    sa.Column('heal_total', sa.Float(), nullable=False),
    sa.Column('gifts_total', sa.Integer(), nullable=False),
    sa.Column('combo_count', sa.Integer(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['battle_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('gift_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('combo_count', sa.Integer(), nullable=False),
    sa.Column('xp_delta', sa.Float(), nullable=False),
    sa.Column('target_side', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['battle_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_events')
    op.drop_table('players')
    op.drop_table('battle_sessions')
    op.drop_table('battles')
    op.drop_table('settings')
    op.drop_table('music_tracks')
    op.drop_table('gifts')
    op.drop_table('combo_tiers')
    op.drop_table('characters')
    # ### end Alembic commands ###
